# 빌드 시 무시할 폴더 지정
exclude:
  - admin_ui/node_modules
  - node_modules
  - vendor
  - .github
  - .idea

# plans 폴더 안의 파일들은 Liquid 문법 검사를 하지 않도록 설정
defaults:
  - scope:
      path: "plans"
    values:
      liquid: false