from __future__ import annotations

import json
from collections.abc import Sequence
from uuid import UUID

from agent_trading.db.row_mapper import row_to_entity
from agent_trading.db.transaction import TransactionManager
from agent_trading.domain.entities import AgentRunEntity


class PostgresAgentRunRepository:
    """PostgreSQL implementation of ``AgentRunRepository``.

    Stores agent execution runs in the ``trading.agent_runs`` table.
    The ``agent_run_id`` is generated by the caller (recorder); this
    repository only persists the entity as-is.
    """

    __slots__ = ("_tx",)

    def __init__(self, tx: TransactionManager) -> None:
        self._tx = tx

    async def add(self, run: AgentRunEntity) -> AgentRunEntity:
        row = await self._tx.connection.fetchrow(
            """
            INSERT INTO trading.agent_runs
                (agent_run_id, decision_context_id, agent_type,
                 model_id, prompt_id, temperature, seed,
                 raw_output_uri, structured_output_json,
                 status, started_at, completed_at, created_at)
            VALUES ($1, $2, $3,
                    $4, $5, $6, $7,
                    $8, $9::jsonb,
                    $10, $11, $12, $13)
            RETURNING *
            """,
            run.agent_run_id,
            run.decision_context_id,
            run.agent_type,
            run.model_id,
            run.prompt_id,
            run.temperature,
            run.seed,
            run.raw_output_uri,
            json.dumps(run.structured_output_json)
            if run.structured_output_json is not None
            else None,
            run.status,
            run.started_at,
            run.completed_at,
            run.created_at,
        )
        return row_to_entity(row, AgentRunEntity)

    async def get(self, agent_run_id: UUID) -> AgentRunEntity | None:
        """Get a single agent run by its UUID."""
        row = await self._tx.connection.fetchrow(
            "SELECT * FROM trading.agent_runs WHERE agent_run_id = $1",
            agent_run_id,
        )
        return row_to_entity(row, AgentRunEntity) if row else None

    async def list_by_decision_context(
        self, decision_context_id: UUID
    ) -> list[AgentRunEntity]:
        rows = await self._tx.connection.fetch(
            "SELECT * FROM trading.agent_runs "
            "WHERE decision_context_id = $1 "
            "ORDER BY started_at DESC",
            decision_context_id,
        )
        return [row_to_entity(r, AgentRunEntity) for r in rows]

    async def list_by_decision_contexts(
        self, decision_context_ids: Sequence[UUID], *, agent_type: str | None = None
    ) -> dict[UUID, list[AgentRunEntity]]:
        if not decision_context_ids:
            return {}
        if agent_type is not None:
            # agent_type으로 좁히면 불필요한 타입의 큰 structured_output_json까지
            # 네트워크로 끌어오지 않는다 — compliance 조회처럼 특정 타입 1개만
            # 필요한 호출자에게 중요한 최적화(실측: 500개 context 기준 agent_runs
            # 쿼리가 80ms → 이 필터 없이는 해당 context들의 전체 run이 다 오므로).
            rows = await self._tx.connection.fetch(
                "SELECT * FROM trading.agent_runs "
                "WHERE decision_context_id = ANY($1::uuid[]) AND agent_type = $2 "
                "ORDER BY decision_context_id, started_at DESC",
                list(set(decision_context_ids)),
                agent_type,
            )
        else:
            rows = await self._tx.connection.fetch(
                "SELECT * FROM trading.agent_runs "
                "WHERE decision_context_id = ANY($1::uuid[]) "
                "ORDER BY decision_context_id, started_at DESC",
                list(set(decision_context_ids)),
            )
        result: dict[UUID, list[AgentRunEntity]] = {}
        for row in rows:
            entity = row_to_entity(row, AgentRunEntity)
            result.setdefault(entity.decision_context_id, []).append(entity)
        return result

    async def list_all(self, limit: int = 100) -> list[AgentRunEntity]:
        rows = await self._tx.connection.fetch(
            "SELECT * FROM trading.agent_runs "
            "ORDER BY started_at DESC LIMIT $1",
            limit,
        )
        return [row_to_entity(r, AgentRunEntity) for r in rows]
